FROM debian:buster
ARG VER="12-6"

RUN dpkg --add-architecture arm64
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list; \
    sed -i s/security.debian.org/archive.debian.org/g /etc/apt/sources.list; \
    apt-get update; \
    apt-get -y install -o APT::Immediate-Configure=false \
        git curl wget vim ninja-build crossbuild-essential-arm64 zlib1g-dev:arm64 libbz2-dev:arm64 software-properties-common

RUN wget https://github.com/Kitware/CMake/releases/download/v3.31.0/cmake-3.31.0-linux-x86_64.sh; \
    chmod +x cmake-3.31.0-linux-x86_64.sh; \
    ./cmake-3.31.0-linux-x86_64.sh --skip-license --prefix=/usr/local;

RUN wget -O cuda-x64.deb  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
RUN wget -O cuda-sbsa.deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/cross-linux-sbsa/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-x64.deb && dpkg -i cuda-sbsa.deb
RUN apt-get update
RUN apt-get install -y cuda-nvcc-${VER} cuda-nvcc-cross-sbsa-${VER} cuda-cudart-cross-sbsa-${VER} libcublas-cross-sbsa-${VER}

RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain stable -y
ENV PATH=/root/.cargo/bin:$PATH
